### ISSUE TITLE
Windows named pipe error

### ISSUE THREAD

**Issue by prakhargurunani** [Samwalton9/hashtags#24]
@Samwalton9 
I ran the command 'docker-compose up --build' inside the project directory. It gives me this error -
![Screenshot (50)](https://user-images.githubusercontent.com/43035576/55134180-13067500-514e-11e9-80db-90b7118605ef.png)
Please help.

**Comment by Samwalton9** [comment]
Some potential solutions:

- Run command prompt as administrator
- Restart the Docker software

Other possible solutions are listed at https://github.com/docker/toolbox/issues/725

**Comment by prakhargurunani** [comment]
Oh ! I was using the linux container. I just had to switch to windows container.
Now no errors. So closing this issue.
