### ISSUE TITLE
Add default to EXCLUDED

### ISSUE THREAD

**Issue by Samwalton9** [Samwalton9/hashtags#4]
#default is a magic word we should exclude from collection.

https://github.com/Samwalton9/hashtags/blob/master/scripts/common.py#L4

**Comment by Samwalton9** [comment]
Also #mw

**Comment by ParthS007** [comment]
@Samwalton9 I want to work on it.

**Comment by Samwalton9** [comment]
Sorry @ParthS007 - @Jain-Aditya submitted a PR already! Check out Phabricator for more open tasks: https://phabricator.wikimedia.org/project/view/3229/
